env = Environment(CCFLAGS = '-g -Wall -DUSE_DEBUG',
CPPPATH=['/usr/local/protobuf-2.5.0/include','/usr/local/protobuf-c-0.15/include','/usr/local/Cellar/libevent/2.0.21/include'],
LIBPATH=['/usr/local/protobuf-2.5.0/lib','/usr/local/protobuf-c-0.15/lib','/usr/local/lib','.'])
lib_files = Split('riak.c riak_utils.c riak_pb_message.c riak.pb-c.c riak_kv.pb-c.c')

env.Library('riak_c_client', lib_files)
env.Program('riak_c_client','main.c', LIBS=['riak_c_client', 'event_core', 'event_extra', 'iconv', 'pthread', 'protobuf', 'protobuf-c'])


conf = Configure(env)
if not conf.CheckLib('pthread'):
  print 'Did not find pthread lib, exiting!'
  Exit(1)

if not conf.CheckLib('protobuf'):
  print 'Did not find protobuf lib, exiting!'
  Exit(1)

if not conf.CheckLib('protobuf-c'):
  print 'Did not find protobuf-c lib, exiting!'
  Exit(1)

if not conf.CheckLib('iconv'):
  print 'Did not find iconv lib, exiting!'
  Exit(1)

if not conf.CheckLib('curl'):
  print 'Did not find curl lib, exiting!'
  Exit(1)

if not conf.CheckLib('libevent'):
  print 'Did not find libevent, exiting!'
  Exit(1)


env = conf.Finish()

