env = Environment(CCFLAGS = '-Wall')
lib_files = Split('riak.c pb_messages.c pb_transport.c riak.pb-c.c riak_kv.pb-c.c')
env.Library('riak_c_client', lib_files)
env.Program('main.c', LIBS=['riak_c_client', 'iconv', 'pthread', 'protobuf', 'protobuf-c'], LIBPATH='.')


conf = Configure(env)
if not conf.CheckLib('pthread'):
  print 'Did not find pthread lib, exiting!'
  Exit(1)

if not conf.CheckLib('protobuf'):
  print 'Did not find protobuf lib, exiting!'
  Exit(1)

if not conf.CheckLib('protobuf-c'):
  print 'Did not find protobuf-c lib, exiting!'
  Exit(1)

if not conf.CheckLib('iconv'):
  print 'Did not find iconv lib, exiting!'
  Exit(1)


env = conf.Finish()

